apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilr-backend-deployment
  labels:
    app: ilr-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ilr-backend-v1
  template:
    metadata:
      labels:
        app: ilr-backend-v1
    spec:
      containers:
        - name: ilr-backend-server
          image: sahilpatel93/ilr-backend:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred
